### ISSUE TITLE
Mixpanel broken?

### ISSUE THREAD

**Issue by aalimovs** [adopted-ember-addons/ember-metrics#211]
Hi, new to `ember-metrics` and haven't used Mixpanel for years.

I've installed the addon, set it up, Google Analytics works fine but Mixpanel doesn't. I'm inspecting the request it sends, I can see Mixpanel returns a `0` back. 

Adding `&verbose=1` returns:

```
{
    "status": 0,
    "error": "a temporary failure occurred"
}
```

Here's a decoded base64 of what Mixpanel tries to send:

```json
{
	"event": "mp_page_view",
	"properties": {
		"$os": "Mac OS X",
		"$browser": "Chrome",
		"$referrer": "http://localhost:4200/foos",
		"$referring_domain": "localhost:4200",
		"$current_url": "http://localhost:4200/foos",
		"$browser_version": 69,
		"$screen_height": 900,
		"$screen_width": 1440,
		"mp_lib": "web",
		"$lib_version": "2.22.4",
		"distinct_id": "foo_123",
		"$initial_referrer": "http://localhost:4200/foos",
		"$initial_referring_domain": "localhost:4200",
		"mp_page": "http://localhost:4200/foos",
		"mp_referrer": "http://localhost:4200/foos",
		"mp_browser": "Chrome",
		"mp_platform": "Mac OS X",
		"token": "b1d175487b627762454a409c45ef5foo"
	}
}
```

The event is `mp_page_view`. 

However, I did find that `mp_page_view` seems to be deprecated and Mixpanel's [server just ignores it now](https://help.mixpanel.com/hc/en-us/articles/115004568086-History-Of-mp-page-view-Event)? 

I can see a request loading http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js, so not sure why a latest version is sending a deprecated event? Nothing in the adapter explicitly sends `mp_page_view`.

What am I missing?

**Comment by scottkidder** [comment]
@aalimovs Were you able to figure this out?

**Comment by aalimovs** [comment]
@scottkidder no, ended up not using Mixpanel

**Comment by jherdman** [comment]
Closing for now. Please feel free to open a new issue should this problem arise again.

**Comment by juliushuck** [comment]
I'm not using this repo whatsoever, but I had the same error message. I'm using Google Tag Manager.

I wanted to seperate production and development evnironment wiht a Google Tag Manager variable for the Mixpanel token.

I also got the "a temporary failure occurred" error message in the developer tools on the mixpanel track request.

Turns out I messed up the environment check and the project token was undefined on at least some events.

In detail, I had the Mixpanel project token in a gtagmanager variable with the type global js variable, changed it to the js function type, returned the correct token depending on the env and now it works perfectly fine.

If you have any questions, please ask.
